project:
  title: "lecture-notes"
  render:
    - outline*.qmd
    - running.qmd
    - readfile.qmd
    - graphs.qmd
    - graphs_c33.qmd
    - numsum.qmd
    - choosing.qmd
    - bootstrap_R.qmd
    - inference*.qmd
    - reports.qmd
    - tidy*.qmd
    - wider_wrong.qmd
    - windmill.qmd
    - asphalt.qmd
    - with_categ.qmd
    - functions.qmd
    - dates_and_times.qmd
    - dip.qmd
    - vector_matrix.qmd
    - bootstrap.qmd
    - bootstrap_c33.qmd
    - stan.qmd
    - regression.qmd
    - logistic.qmd
    - survival.qmd
    - anova.qmd
    - ancova.qmd
    - manova.qmd
    - profile.qmd
    - discrim.qmd
    - cluster.qmd
    - mapping.qmd
    - princomp.qmd
    - factor.qmd
    - multiway.qmd
    
format: 
  revealjs:
     df-print: paged
     scrollable: true
     embed-resources: true
  beamer:
    incremental: false
execute:
  echo: true
  freeze: auto
editor: 
  markdown: 
    wrap: 72
 