project:
  title: "lecture-notes"
format: 
  revealjs:
     df-print: paged
     scrollable: true
     embed-resources: true
  beamer:
    incremental: false
execute:
  echo: true
# freeze: auto
editor: 
  markdown: 
    wrap: 72


